name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm i

      - name: Generate documentation
        run: |
          npx typedoc

      - name: Clone docs repo
        run: |
          git clone https://${{ secrets.DOCS_TOKEN }}@github.com/Devang0215/Documentation-Repo.git docs-repo

      - name: Copy documentation
        run: |
          rm -rf docs-repo/*
          cd docs-repo
          mkdir documentation-test
          cp -R Code-Documentation/docs/* docs-repo/documentation-test/

      - name: Commit changes
        run: |
          cd docs-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "Auto update documentation"
          git push